//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEBFORM2WITHREFERNCEOFEXISTINGWEBAPI.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.webapiSoap")]
    public interface webapiSoap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        WEBFORM2WITHREFERNCEOFEXISTINGWEBAPI.ServiceReference1.HelloWorldResponse HelloWorld(WEBFORM2WITHREFERNCEOFEXISTINGWEBAPI.ServiceReference1.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<WEBFORM2WITHREFERNCEOFEXISTINGWEBAPI.ServiceReference1.HelloWorldResponse> HelloWorldAsync(WEBFORM2WITHREFERNCEOFEXISTINGWEBAPI.ServiceReference1.HelloWorldRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public WEBFORM2WITHREFERNCEOFEXISTINGWEBAPI.ServiceReference1.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(WEBFORM2WITHREFERNCEOFEXISTINGWEBAPI.ServiceReference1.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public WEBFORM2WITHREFERNCEOFEXISTINGWEBAPI.ServiceReference1.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(WEBFORM2WITHREFERNCEOFEXISTINGWEBAPI.ServiceReference1.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface webapiSoapChannel : WEBFORM2WITHREFERNCEOFEXISTINGWEBAPI.ServiceReference1.webapiSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class webapiSoapClient : System.ServiceModel.ClientBase<WEBFORM2WITHREFERNCEOFEXISTINGWEBAPI.ServiceReference1.webapiSoap>, WEBFORM2WITHREFERNCEOFEXISTINGWEBAPI.ServiceReference1.webapiSoap {
        
        public webapiSoapClient() {
        }
        
        public webapiSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public webapiSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public webapiSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public webapiSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WEBFORM2WITHREFERNCEOFEXISTINGWEBAPI.ServiceReference1.HelloWorldResponse WEBFORM2WITHREFERNCEOFEXISTINGWEBAPI.ServiceReference1.webapiSoap.HelloWorld(WEBFORM2WITHREFERNCEOFEXISTINGWEBAPI.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            WEBFORM2WITHREFERNCEOFEXISTINGWEBAPI.ServiceReference1.HelloWorldRequest inValue = new WEBFORM2WITHREFERNCEOFEXISTINGWEBAPI.ServiceReference1.HelloWorldRequest();
            inValue.Body = new WEBFORM2WITHREFERNCEOFEXISTINGWEBAPI.ServiceReference1.HelloWorldRequestBody();
            WEBFORM2WITHREFERNCEOFEXISTINGWEBAPI.ServiceReference1.HelloWorldResponse retVal = ((WEBFORM2WITHREFERNCEOFEXISTINGWEBAPI.ServiceReference1.webapiSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WEBFORM2WITHREFERNCEOFEXISTINGWEBAPI.ServiceReference1.HelloWorldResponse> WEBFORM2WITHREFERNCEOFEXISTINGWEBAPI.ServiceReference1.webapiSoap.HelloWorldAsync(WEBFORM2WITHREFERNCEOFEXISTINGWEBAPI.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<WEBFORM2WITHREFERNCEOFEXISTINGWEBAPI.ServiceReference1.HelloWorldResponse> HelloWorldAsync() {
            WEBFORM2WITHREFERNCEOFEXISTINGWEBAPI.ServiceReference1.HelloWorldRequest inValue = new WEBFORM2WITHREFERNCEOFEXISTINGWEBAPI.ServiceReference1.HelloWorldRequest();
            inValue.Body = new WEBFORM2WITHREFERNCEOFEXISTINGWEBAPI.ServiceReference1.HelloWorldRequestBody();
            return ((WEBFORM2WITHREFERNCEOFEXISTINGWEBAPI.ServiceReference1.webapiSoap)(this)).HelloWorldAsync(inValue);
        }
    }
}
